### ISSUE TITLE
[Crash] Crashes when loading server

### ISSUE THREAD

**Issue by A5ho9999** [btwonion/telekinesis#10]
Minecraft 1.20.1
Fabric Loader 0.14.22
Mod version: https://modrinth.com/plugin/telekinesis/version/fabric-2.3.3-1.20

Crashes on start up when starting a server

Log: https://gist.github.com/A5ho9999/2b032aaaf9a3b16b3bb0e46e337465ee

Edit: Any version above https://modrinth.com/plugin/telekinesis/version/fabric-2.3.1-1.20.1 results in same error (the 1.20.2 update and above) which most likely means they aren't compatible with 1.20.1 and below anymore

**Comment by btwonion** [comment]
thanks for your report. so 2.3.1-1.20.1 works right?

**Comment by A5ho9999** [comment]
Yup, but any after that don't.

**Comment by btwonion** [comment]
i changed the version compatibilites to be correct. you can go with 2.3.1-1.20.1 then i suppose
