### ISSUE TITLE
Destroying armor upon death

### ISSUE THREAD

**Issue by ginsm** [btwonion/telekinesis#15]
Tested this with `telekinesis-3.0.0-beta6-1.20.1` with the default config and no other mods installed; only the required ones.

Simply put some armor on yourself, die, and it'll disappear rather than dropping.

**Comment by btwonion** [comment]
Hi,
thanks for the report.
I'm currently on vacation and will probably not fix it in the next days.
Nevertheless, feel free to report more occuring errors.

**Comment by btwonion** [comment]
this error is fixed with this commit and release 3.0.0: 94f6928b454218d9696f96245338647e5c125b63
