### ISSUE TITLE
Breaking a Boat with an item enchanted with Telekinesis Duplicates the boat many times

### ISSUE THREAD

**Issue by f-raZ0R** [btwonion/telekinesis#16]
Reproduced on 1.20.1 with just telekinesis (and a couple qol mods in this video, but it still happens without them)
for some reason, the enchant putting the item into your inventory completely cancels the boat actually breaking, meaning you can just do it.. again and again, until your inventory fills up.
https://github.com/user-attachments/assets/403d6673-3e49-4552-97c6-fc5ae0f4ed5b

**Comment by btwonion** [comment]
okayyy thats interesting. Thanks for the report. A fix will come in the following days.

**Comment by btwonion** [comment]
hi,
no need to close. I will hold this open until it's fixed

**Comment by btwonion** [comment]
Thanks for the report!
