### ISSUE TITLE
Feature : Sneaking

### ISSUE THREAD

**Issue by sternschnaube** [btwonion/telekinesis#4]
I would love to have a option to receive everything just if you're sneaking.

**Comment by btwonion** [comment]
hi,
thank you for your feature request.
how long should the item stay whitelisted? until the game stops or permanently?

**Comment by sternschnaube** [comment]
Hello @btwonion, I'm not sure if I understand you correctly.
Sorry for that.

I would love to keep it always on - just if I sneak, I insert the breaking blocks/mob drops directly into my inventory.

**Comment by btwonion** [comment]
oh sorry. i was thinking about another mod...
you mean telekinesis is disabled until you sneak right?

**Comment by sternschnaube** [comment]
Ah 😊
Yep, turning the effect / enchantment off while you are not sneaking.

**Comment by btwonion** [comment]
okay got you. i will add this in the next few days.
thank you

**Comment by sternschnaube** [comment]
Awesome to hear, thanks!!

**Comment by btwonion** [comment]
hi, your feature was implemented with the latest release: https://github.com/btwonion/telekinesis/releases/tag/2.2.0-1.20

**Comment by sternschnaube** [comment]
Thanks alot!! Works perfect 🥳
