### ISSUE TITLE
Exp drops doesn't work with bows?

### ISSUE THREAD

**Issue by someonedeepintheinternet** [btwonion/telekinesis#6]
Hello, I'd like to ask if it were possible to move the dropped Experience by a mob that got shot by an bow/crossbow into the inventory. If this was already added, then I would report this as an bug.

**Comment by btwonion** [comment]
hi, thanks for your report.
i need some more information:
- on what platform are you playing? (fabric/paper)
- what version are you using?

**Comment by someonedeepintheinternet** [comment]
I play on Fabric 1.20.1, fabric-loader-0.14.21 with
 Telekinesis-fabric-2.2.1

**Comment by btwonion** [comment]
fixed with https://modrinth.com/plugin/telekinesis/version/v2.2.2-1.20.1
