### ISSUE TITLE
[Major Bug] Overriding death functions

### ISSUE THREAD

**Issue by A5ho9999** [btwonion/telekinesis#7]
Mod Version: https://modrinth.com/plugin/telekinesis/version/v2.2.1-1.20.1
MC Version: Fabric 1.20.1 
Loader: 0.14.21

Telekinesis is overriding player death functions, resulting in conflicting with many other mods.

- Gravestones are being blocked from generating: [Forgotten Graves](https://modrinth.com/mod/forgotten-graves)
- Trinkets aren't being removed on death and kept on respawn: [Trinkets](https://modrinth.com/mod/trinkets) with [Things](https://modrinth.com/mod/things) and [Icarus](https://modrinth.com/mod/icarus)
- Backpacks while on Player backs are being completely deleted, not recoverable [Traveler's Backpack](https://modrinth.com/mod/travelersbackpack)

No Errors or Logs are present regarding either. Issue was not present in previous versions

**Comment by btwonion** [comment]
hi,
unfortunately is overriding the death function here the only way to hold the player instance.
in the cases you mentioned the other mods have to add compatibility for mines.

**Comment by A5ho9999** [comment]
I don't believe that is the case actually, it is your mod that is overriding a basic function (which shouldn't be for this case). It is your mod causing issues with multiple others, having to go more than 4 other mod developers to ask them for compatibility is not okay. It is not the only way as I said, previous versions of the mod didn't have this issue.

I really hope you take the time to look into this properly and come up with a better solution.

**Comment by btwonion** [comment]
should be fixed with this release: https://github.com/btwonion/telekinesis/releases/tag/fabric-2.3.0-1.20.1
i did only test the changes with Forgotten Graves. please let me know if there are still errors occuring

**Comment by A5ho9999** [comment]
Appears to be working correctly now with all the mods, thank you for taking the time to fix it.
