### ISSUE TITLE
Suggestion: Adding permission option

### ISSUE THREAD

**Issue by h14turkiye** [btwonion/telekinesis#8]
Add requirePermission option on the config.

**Comment by btwonion** [comment]
for what should a permission be required? for the individual types of what is enabled for telekinesis or for telekinesis in general?

**Comment by h14turkiye** [comment]
I don't think code will benefit for individual types, but users would benefit from it. I have seen the code although it is pretty clean, I don't think you can implement it easily as you would "in general". So in my opinion you can implement individual types if it is clean as the general one. With this permission option you can remove the enchantment and give the permission for the VIPS. Becoming a no drop plugin and an enchantment plugin at the same time.

**Comment by btwonion** [comment]
removing the enchantment for specific players on servers is pain.. but i could lock the functionality behind a permission

**Comment by h14turkiye** [comment]
Yeah just add permission to the TelekinesisCheck, to block functionality for the people without the permission. What i meant earlier by removing the enchantment was to use onByDefault and disabling "enchantment" value in the config. Intending to use it as a no drop plugin. 

You might also change the way you handle onByDefault, like a bypass working for the people who have the permission. If you don't have the permission the enchantment is a must.

**Comment by btwonion** [comment]
are you suggesting this for paper or fabric?

**Comment by btwonion** [comment]
this version adds the feature.. please let me know if it's fitting your expectations:
https://modrinth.com/plugin/telekinesis/version/v2.3.0-1.20.1

**Comment by h14turkiye** [comment]
Yes it was for paper, and you did exactly what I want. Thank you.

**Comment by btwonion** [comment]
thank you
